---
deployment:
  tasks:
    - export DEPLOYPATH=/home/carsoijc/public_html/
    - export SOURCEPATH=/home/carsoijc/deployment/
    - /bin/cp -R $SOURCEPATH/build/* $DEPLOYPATH/
    - /bin/cp -R $SOURCEPATH/api $DEPLOYPATH/
    - /bin/cp $SOURCEPATH/.htaccess $DEPLOYPATH/
    - /bin/chmod 644 $DEPLOYPATH/.htaccess
    - /bin/chmod 755 $DEPLOYPATH/api/
    - /bin/find $DEPLOYPATH/api -type f -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH/api -type d -exec chmod 755 {} \;
